version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - python -m pip install --upgrade pip
      - pip install --upgrade --force-reinstall boto3 awscli
      - pip install -r $CODEBUILD_SRC_DIR/sagemaker_pipeline/requirements.txt

  pre_build:
    commands:
      - echo Pre-build phase...
      - echo Pipeline name
      - export PIPELINE_NAME=${CODEBUILD_INITIATOR#codepipeline/}
      - echo $PIPELINE_NAME

  build:
    commands:
      - echo Build phase...
      - echo Build started on `date`
      - echo Run the workflow script
      - cd $CODEBUILD_SRC_DIR/sagemaker_pipeline
      - export PYTHONBUFFERED=TRUE
      - export PIPELINE_NAME=$PIPELINE_NAME
      - |
        if [ "$PIPELINE_STAGE" = "DEPLOY" ]; then
            python src/pipeline/deploy_model.py 
        else
            python src/pipeline/run_pipeline.py 
        fi
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on `date`

